### ISSUE TITLE
Photo or video

### ISSUE THREAD

**Issue by hrupin** [androidbuffer/Kotlinfilepicker#3]
Hello.
Thank you very much for the library. Super comfortable and fast.

I have a question: how can it be used to call the camera where the user can switch a photo or video?

**Comment by androidbuffer** [comment]
Hey, @hrupin thanks for using the library. It seems this can't be done for now as there is no SDK level support for capturing the video as well as an image and have file locations as well. Even if we capture the media but won't be able to get the location of the file created. we have to create a custom camera to do which is another project in itself. Hope this information helps, closing for now, please reopen the issue or create a new one if you find something else 
thanks.
