### ISSUE TITLE
Android Pie Issue

### ISSUE THREAD

**Issue by Gorebar** [androidbuffer/Kotlinfilepicker#6]
I was trying to import in Android Pie version and.. simple, not works. 

Exactly on method `readPathFromUri`:

When it try to get the DocumentId, get a unknown path/id

` val docId = DocumentsContract.getDocumentId(uri)`

Any suggestions?

**Comment by worstkiller** [comment]
hi Gorebar thanks for reporting since we haven't supported Android 10 yet so you can expect it to break. but we are looking into the issue and will get back soon.

**Comment by Gorebar** [comment]
> hi Gorebar thanks for reporting since we haven't supported Android 10 yet so you can expect it to break. but we are looking into the issue and will get back soon.

Well... Sure, no Android 10 but... What about Android 9 (Pie) and what about Android 8 (Oreo)?

Not works, for example, from SDCARD or Download folder. The second one (Donwload) it's a big problem I think so... :(

**Comment by worstkiller** [comment]
Hi @Gorebar can you please elaborate the issue with some steps to reproduce or some video or some git repo, that will help us sort this out. We tried producing the issue but seems to work fine for us on Android 10 and Android 9, 8 stock versions.
thanks
